Use new gather syntax and compute averages

diff --git a/opt/flight/libexec/commands/carbon b/opt/flight/libexec/commands/carbon
--- a/opt/flight/libexec/commands/carbon
+++ b/opt/flight/libexec/commands/carbon
@@ -16,6 +16,12 @@ if ! which jq >/dev/null 2>&1 ; then
     exit 1
 fi
 
+# Exit if no Gather
+if !(rpm -qa |grep flight-gather -q) ; then
+    echo "Cannot find Gather. Gather is required for the program to function"
+    exit 1
+fi
+
 # Prepare log stuff
 if [ ! -d $LOG_DIR ] ; then
     mkdir $LOG_DIR
@@ -38,27 +44,7 @@ fi
 # - Number of PSUs - Not sure how this could possibly be worked out for VMs, potentially with IPMI on hardware
 # - Number of GPUs - Not yet supported in Boavizta
 
-## Use flight-gather info if present
-if rpm -qa |grep flight-gather -q ; then
-    PLATFORM=$(/opt/flight/bin/flight gather show --force |grep '^:platform:' |awk '{print $2}')
-    GATHER=true
-else
-    plat_query=$(sudo dmidecode -t system |grep -E '^[[:blank:]]+Manufacturer' |awk '{print $2}')
-    case $plat_query in
-        "OpenStack")
-            PLATFORM="$plat_query"
-            ;;
-        "Amazon")
-            PLATFORM="AWS"
-            ;;
-        "Microsoft")
-            PLATFORM="Azure"
-            ;;
-        *)
-            PLATFORM="Unknown"
-            ;;
-    esac
-fi
+PLATFORM=$(flight gather show .platform --force)
 
 ## Determine if AWS or Alces Cloud instance (makes life much easier if it is)
 if [[ $PLATFORM == "AWS"  ]] || [[ $PLATFORM == "Alces Cloud" ]] ; then
@@ -67,53 +53,23 @@ if [[ $PLATFORM == "AWS"  ]] || [[ $PLATFORM == "Alces Cloud" ]] ; then
 fi
 
 ## Figure system info out
-if [ ! -z $GATHER ] ; then
-    # Grab some data from gather
-    NUMCPUS=$(flight gather show |grep -E '^[[:blank:]]+CPU' |wc -l)
-    NUMCORESPERCPU=$(flight gather show |grep -m 1 -E '^[[:blank:]]+:cores:' |awk '{print $2}')
-else
-    # Work it out
-    NUMCPUS=$(grep "physical id"  /proc/cpuinfo | sort -u | wc -l)
-    NUMCORESPERCPU=$(grep -m 1 '^cpu cores' /proc/cpuinfo |awk '{print $4}') # Assume all CPUs have same cores per CPU
-fi
-
-CPUMODEL=$(grep -m 1 '^model name' /proc/cpuinfo |sed 's/.*: //g;s/ @.*//g')
-#CPUMANUFACTURER=$(dmidecode -t processor |grep -m 1 -E '[[:blank:]]+Manufacturer' |awk '{print $2}')
-#CPUFAMILY=$(dmidecode -t processor |grep -m 1 -E '[[:blank:]]+Family' |awk '{print $2}')
+# Grab some data from gather
+NUMCPUS=$(flight gather show .cpus.units)
+NUMCORESPERCPU=$(flight gather show .cpus.cores_per_cpu)
+CPUMODEL=$(flight gather show .cpus.cpu_data.[CPU0].model)
 
 # Memory distribution
-NUMDIMMS=$(sudo dmidecode -t memory |grep -E '^[[:blank:]]+Locator' |wc -l) # In GB
-GBPERDIMM=$(sudo dmidecode -t memory |grep -m 1 -E '^[[:blank:]]+Size' |awk '{print $2}') # Assume all dimms have same amount
+NUMDIMMS=$(flight gather show .ram.units)
+GBPERDIMM=$(fligt gather show .ram.capacity_per_unit)
 
 # Disks
-DISKSJSON=""
-DISKSINFO=""
 disks=$(ls /sys/block)
 for disk in $disks ; do
-    rotate=$(cat /sys/block/$disk/queue/rotational)
-    case $rotate in
-        0)
-            disktype="ssd"
-            ;;
-        1)
-            disktype="hdd"
-            ;;
-        *)
-            echo "Unknown disk type for $disk"
-            echo "Can't determine if SSD or HDD"
-            exit 1
-            ;;
-    esac
-    size=$(($(lsblk -b --output SIZE -n -d /dev/$disk)/1024/1024/1024)) # Size in GB, rough estimate should round okay but larger sizes may differ
-    DISKSJSON="{\"units\": 1, \"type\": \"$disktype\", \"capacity\": $size},$DISKSJSON"
-    DISKSINFO="${size}GB $disktype, $DISKSINFO"
+	size=$(flight gather show .disks.[$disk].size)
+	disktype=$(flight gather show .disks.[$disk].type)
+	DISKSJSON="{\"units\": 1, \"type\": \"$disktype\", \"capacity\": $size},$DISKSJSON"
+	DISKSINFO="${size}GB $disktype, $DISKSINFO"
 done
-
-# GPU - Not sure
-
-#
-# Determine Power
-#
 
 case $PLATFORM in
     "AWS")
@@ -203,27 +159,46 @@ FULLLOADREQUEST="$BASEREQUEST
 }
 "
 
+load_avg_15min=$(uptime| awk -F'load average: ' '{print $2}' | cut -d ',' -f3 | tr -d ' ')
+percentage_15min=$(echo "scale=2; ($load_avg_15min / $(nproc)) * 100" | bc)
+
+AVERAGELOADREQUEST="$BASEREQUEST
+  \"usage\": {
+    \"usage_location\": \"$LOCATION\",
+    \"hours_use_time\": 1,
+    \"hours_life_time\": 1,
+    \"time_workload\": $percentage_15min
+  }
+}
+"
+
 #
 # Get GWP from Specs
 #
 
 NOLOAD=$(curl -s -X 'POST' \
-  'https://api.boavizta.org/v1/server/?verbose=true&criteria=gwp' \
+  'https://api.boavizta.org/v1/server/?verbose=false&criteria=gwp' \
   -H 'accept: application/json' \
   -H 'Content-Type: application/json' \
   -d "$NOLOADREQUEST" |jq '.impacts.gwp.use.value')
 
 HALFLOAD=$(curl -s -X 'POST' \
-  'https://api.boavizta.org/v1/server/?verbose=true&criteria=gwp' \
+  'https://api.boavizta.org/v1/server/?verbose=false&criteria=gwp' \
   -H 'accept: application/json' \
   -H 'Content-Type: application/json' \
   -d "$HALFLOADREQUEST" |jq '.impacts.gwp.use.value')
 
 FULLLOAD=$(curl -s -X 'POST' \
-  'https://api.boavizta.org/v1/server/?verbose=true&criteria=gwp' \
+  'https://api.boavizta.org/v1/server/?verbose=false&criteria=gwp' \
   -H 'accept: application/json' \
   -H 'Content-Type: application/json' \
   -d "$FULLLOADREQUEST" |jq '.impacts.gwp.use.value')
+
+AVERAGELOAD=$(curl -s -X 'POST' \
+  'https://api.boavizta.org/v1/server/?verbose=false&criteria=gwp' \
+  -H 'accept: application/json' \
+  -H 'Content-Type: application/json' \
+  -d "$AVERAGELOADREQUEST" |jq '.impacts.gwp.use.value')
 
 #
 # Get GWP from Instance Type
@@ -280,13 +255,30 @@ FULLLOADINSTANCEREQUEST="{
 }
 "
 
-NOLOADINSTANCE="$(curl -s -X 'POST' -H 'accept: application/json' 'https://api.boavizta.org/v1/cloud/instance?verbose=true&criteria=gwp' -H 'Content-Type: application/json' -d "$NOLOADINSTANCEREQUEST" |jq '.impacts.gwp.use.value')"
-HALFLOADINSTANCE="$(curl -s -X 'POST' -H 'accept: application/json' 'https://api.boavizta.org/v1/cloud/instance?verbose=true&criteria=gwp' -H 'Content-Type: application/json' -d "$HALFLOADINSTANCEREQUEST" |jq '.impacts.gwp.use.value')"
-FULLLOADINSTANCE="$(curl -s -X 'POST' -H 'accept: application/json' 'https://api.boavizta.org/v1/cloud/instance?verbose=true&criteria=gwp' -H 'Content-Type: application/json' -d "$FULLLOADINSTANCEREQUEST" |jq '.impacts.gwp.use.value')"
+AVERAGELOADINSTANCEREQUEST="{
+\"provider\": \"aws\",
+\"instance_type\": \"$INSTANCE_TYPE\",
+\"usage\" : {
+  \"usage_location\": \"GBR\",
+  \"hours_use_time\": 1,
+  \"hours_life_time\": 1,
+  \"time_workload\": [{
+    \"time_percentage\": 100,
+    \"load_percentage\": $percentage_15min
+    }]
+  }
+}
+"
+
+NOLOADINSTANCE="$(curl -s -X 'POST' -H 'accept: application/json' 'https://api.boavizta.org/v1/cloud/instance?verbose=false&criteria=gwp' -H 'Content-Type: application/json' -d "$NOLOADINSTANCEREQUEST" |jq '.impacts.gwp.use.value')"
+HALFLOADINSTANCE="$(curl -s -X 'POST' -H 'accept: application/json' 'https://api.boavizta.org/v1/cloud/instance?verbose=false&criteria=gwp' -H 'Content-Type: application/json' -d "$HALFLOADINSTANCEREQUEST" |jq '.impacts.gwp.use.value')"
+FULLLOADINSTANCE="$(curl -s -X 'POST' -H 'accept: application/json' 'https://api.boavizta.org/v1/cloud/instance?verbose=false&criteria=gwp' -H 'Content-Type: application/json' -d "$FULLLOADINSTANCEREQUEST" |jq '.impacts.gwp.use.value')"
+AVERAGELOADINSTANCE="$(curl -s -X 'POST' -H 'accept: application/json' 'https://api.boavizta.org/v1/cloud/instance?verbose=false&criteria=gwp' -H 'Content-Type: application/json' -d "$AVERAGELOADINSTANCEREQUEST" |jq '.impacts.gwp.use.value')"
 
 NOLOADAVG=$(echo "print(round(($NOLOAD+$NOLOADINSTANCE)/2,4))" |python)
 HALFLOADAVG=$(echo "print(round(($HALFLOAD+$HALFLOADINSTANCE)/2,4))" |python)
 FULLLOADAVG=$(echo "print(round(($FULLLOAD+$FULLLOADINSTANCE)/2,4))" |python)
+AVERAGELOADAVG=$(echo "print(round(($AVERAGELOAD+$AVERAGELOADINSTANCE)/2,4))" |python)
 
 fi
 
@@ -327,6 +319,9 @@ $HALFLOADREQUEST
 # Full Load
 $FULLLOADREQUEST
 
+# Average Load
+$AVERAGELOADREQUEST
+
 EOF
 
 if [ ! -z $USE_INSTANCE_TYPE ] ; then
@@ -343,6 +338,9 @@ $HALFLOADINSTANCEREQUEST
 
 # Full Load
 $FULLLOADINSTANCEREQUEST
+
+# Average Load
+$AVERAGELOADINSTANCEREQUEST
 EOF
 fi
 
@@ -351,6 +349,7 @@ cat << EOF > $LOG_DIR/data.sh
 NOLOAD=$NOLOAD
 HALFLOAD=$HALFLOAD
 FULLLOAD=$FULLLOAD
+AVERAGELOAD=$AVERAGELOAD
 EOF
 
 if [ ! -z $USE_INSTANCE_TYPE ] ; then
@@ -358,9 +357,11 @@ if [ ! -z $USE_INSTANCE_TYPE ] ; then
 NOLOADINSTANCE=$NOLOADINSTANCE
 HALFLOADINSTANCE=$HALFLOADINSTANCE
 FULLLOADINSTANCE=$FULLLOADINSTANCE
+AVERAGELOADINSTANCE=$AVERAGELOADINSTANCE
 NOLOADAVG=$NOLOADAVG
 HALFLOADAVG=$HALFLOADAVG
 FULLLOADAVG=$FULLLOADAVG
+AVERAGELOADAVG=$AVERAGELOADAVG
 EOF
 fi
 
@@ -370,19 +371,27 @@ report() {
 ## Estimated System Specs
 
 CPU: $NUMCPUS x $CPUMODEL ($NUMCORESPERCPU core(s) per CPU)
+
 RAM: $NUMDIMMS x ${GBPERDIMM}GB
+
 Disks: $(echo "$DISKSINFO" |sed 's/, $//g')
 
 ## Platform & Power Information
 
 Platform: $PLATFORM
+
 Location: $LOCATION
 
 ## Estimated Carbon Consumption (From Specs)
 
 No Load: ${NOLOAD}kgCO2eq/hr
+
 Half Load: ${HALFLOAD}kgCO2eq/hr
+
 Full Load: ${FULLLOAD}kgCO2eq/hr
+
+Average Load: ${AVERAGELOAD}kgCO2eq/hr
+
 EOF
 
   if [ ! -z $USE_INSTANCE_TYPE ] ; then
@@ -391,14 +400,22 @@ EOF
 ## Estimated Carbon Consumption (From Instance Type)
 
 No Load: ${NOLOADINSTANCE}kgCO2eq/hr
+
 Half Load: ${HALFLOADINSTANCE}kgCO2eq/hr
+
 Full Load: ${FULLLOADINSTANCE}kgCO2eq/hr
+
+Average Load: ${AVERAGELOADINSTANCE}kgCO2eq/hr
 
 ## Combined Carbon Consumption Estimate (Average of Previous 2 Estimates)
 
 No Load: $(echo "print(round(($NOLOAD+$NOLOADINSTANCE)/2,4))"  |python)kgCO2eq/hr
+
 Half Load: $(echo "print(round(($HALFLOAD+$HALFLOADINSTANCE)/2,4))"  |python)kgCO2eq/hr
+
 Full Load: $(echo "print(round(($FULLLOAD+$FULLLOADINSTANCE)/2,4))"  |python)kgCO2eq/hr
+
+Average Load: $(echo "print(round(($AVERAGELOAD+$AVERAGELOADINSTANCE)/2,4))"  |python)kgCO2eq/hr
 EOF
   fi
 
@@ -421,6 +438,7 @@ case $action in
     half    Show carbon emissions for node at 50% load
     full    Show carbon emissions for node at 100% load
     min     Show carbon emissions for node at 0% load
+    avg     Show carbon emissions for node at average load from past 15 minutes
     report  Show detailed report for all carbon emission data
 
 EOF
@@ -433,6 +451,9 @@ EOF
     ;;
   "full")
     echo $FULLLOAD
+    ;;
+  "avg")
+    echo $AVERAGELOAD
     ;;
   "platform")
     echo $PLATFORM
